//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rant()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int Id { get; set; }
        public System.DateTime DateTaken { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateReturn { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> licensePlate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
        public virtual Users Users { get; set; }
    }
}
