//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rent
    {
        public int Id { get; set; }
        public System.DateTime DateTaken { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateReturn { get; set; }
        public int UserId { get; set; }
        public Nullable<int> licensePlate { get; set; }
        public int location { get; set; }
        public Nullable<int> carid { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Users Users { get; set; }
    }
}
